<?php
namespace AppBundle\Entity;
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * membersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membersRepository extends \Doctrine\ORM\EntityRepository{
	/**
     * @return result[]
     */
	public function getMembers(){

		$query = $this->createQueryBuilder("m")
			->select("m.firstname", "m.lastname","r.roleName")
			->leftJoin("AppBundle:role_tbl","r","WITH","m.roleId = r.id")
			->where("m.status = 'Active'")
			->Where("r.status = 'Active'")
			->orderBy("m.firstname", "DESC")
			->getQuery();


        return $result = $query->getResult(); 

	}
}
